version: "3"

networks:
  gitea:
    external: false

volumes:
  gitea-data:
    external: true
  gitea-postgres:
    external: true

services:
  server:
    image: gitea/gitea:1.18.1
    container_name: gitea
    environment:
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
      - GITEA__server__PROTOCOL=https
      - GITEA__server__ROOT_URL=https://services.infra.home:4443/
      - GITEA__server__HTTP_PORT=4443
      - GITEA__server__CERT_FILE=/certs/services.infra.home.crt
      - GITEA__server__KEY_FILE=/certs/services.infra.home.key
    restart: always
    networks:
      - gitea
    volumes:
      - gitea-data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - $CERTS_PATH:/certs
    ports:
      - "4443:4443"
      - "222:22"
  
  db:
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - gitea-postgres:/var/lib/postgresql/data  